services:
  litellm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    ports:
      - "4000:4000"
    env_file:
      - .env

