services:
  litellm:
    build: # if you want to build the latest version
      context: .
      dockerfile: Dockerfile
    image: loorisr/litellm-proxy-docker # image from Docker hub
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    ports:
      - "4000:4000"
    env_file:
      - .env
    security_opt:
      - no-new-privileges=true
    read_only: true
    restart: unless-stopped
    cap_drop:
      - ALL
